# Generated by Django 6.0.2 on 2026-04-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wasterequest',
            name='unique_request_per_listing_per_processor',
        ),
    ]
